### ISSUE TITLE
conda install does not work

### ISSUE THREAD

**Issue by cscho-csrc** [sdsucomptox/danrerlib#1]
conda install of danrerlib within a conda environment did not work. 
I got a ModuleNotFound error when trying to import in python command line in the correct environment that the install should have been in. Other packages unique to that environment were able to be imported succesfully.

danrerlib is listed in `conda list`, but it was not present in the directory ~/miniconda3/envs/{env_name}/lib/python{x.x}/site-packages, which is where it should be installed. (checked with `find ~/miniconda3/envs/{env_name} -name "danrerlib"`). Other packages unique to that environment were installed in that location.

I looked at the meta folder for {env_name} and saw that there was an entry for danrerlib. My conclusion is that the package did not install properly, and that python was unable to recognize the Module.

conda uninstall and then pip install worked.

**Comment by sdsucomptox** [comment]
There seemed to be an issue with the building as defined in meta.yaml. It has been modified and verified to properly install.
